### ISSUE TITLE
Check for F1394 - (This fault occurs when a port is down and is in use for fabric)

### ISSUE THREAD

**Issue by dgarzani** [datacenter/ACI-Pre-Upgrade-Validation-Script#28]
Hello,
Suggested enhancement.
Had a Customer that ran the Pre-Upgrade and it didn't flag any of the F1394 Faults that they apparently had.
Now, for some reason F1394 is a minor Severity. Not sure I agree with this in this case the Customer didn't give it the attention that it deserved and subsequently resulted in a postponement of the upgrade Maintenance Window when it was found.

F1394: fltEthpmIfPortDownFabric
Severity: minor
Explanation: This fault occurs when a port is down and is in use for fabric

**Comment by takishida** [comment]
Please upvote (:thumbsup:) for prioritization.

Hi, we haven't decided whether this should be included in the pre-upgrade validations for everyone.

But here is a summary of the fault and its condition to give it a further thought.

## New Validation Request:

### Validation Type (Fault or Config):
Fault Code: F1394
Fault Description: Port is down, reason:notconnect(connected), used by:Fabric

F1394 is raised when a fabric link (a link between ACI spine and leaf, or tier-1 leaf and tier-2 leaf) that used to be up is down.

### Description/Motivation:
In one of the worst cases, the fault may indicate we have an unintended non-full mesh topology where a leaf has connectivity to only one spine even when there are multiple spines because links towards other spines are down for some reason. If an upgrade is performed for the spine with the connectivity, the leaf will lose the reachability to the entire fabric, which causes an outage for all endpoints on that leaf.

But the fault may be raised when the link down is expected, for instance, the node is removed for good.

**Comment by johnjac-cisco** [comment]
The obvious situation I think this would avoid would be a leaf with uplinks to 2 spines, if link(s) to one spine are down the leaf could be come isolated during spine upgrades.
